version: 2

references:
  doc: &doc
    run:
      name: index.html-exists
      command: |
        test -f index.html
jobs:

  test_ubuntu_latest:
    docker:
      - image: ubuntu:latest
    working_directory: ~/cxworker
    steps:
      - checkout
      - *doc

workflows:

  version: 2
  test-doc-exists:
    jobs:
      - test_ubuntu_latest

