version: 2

references:

  ubuntu_install: &ubuntu_install
    run:
      name: Install dependencies on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip curl
        pip3 install -e .
        echo "$(tail -n +2 cxworker/manage.py)" > cxworker/manage.py  # remove gevent monkey patch (it breaks sphinx)

  install: &install
    run:
      name: Install dependencies and cxworker on Archlinux
      command: |
        set -x
        VER="17.11.0-ce"
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/test/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        mv /tmp/docker/* /usr/bin
        pacman --noconfirm --needed -Syu minio
        mkdir examples/docker/cxflow_example/ssh
        echo $PRIVATE_SSH_KEY_PRIVATE | tr ' ' '\n' | base64 -d > examples/docker/cxflow_example/ssh/id_rsa
        pip install -e .

  add_rw_key: &add_rw_key
    add_ssh_keys:
      fingerprints:
        - "bd:18:69:44:c4:97:94:f2:03:ba:db:dd:29:2e:cf:f2"

  test: &test
    run:
      name: Run tests.
      command: |
        python setup.py test

  doc: &doc
    run:
      name: Generate documentation
      command: |
        bash <(curl -fsSL https://raw.githubusercontent.com/Cognexa/ci-utils/master/doc_deploy.sh)

jobs:

  test_archlinux:
    docker:
      - image: cognexa/cxflow:latest
    working_directory: ~/cxworker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.11.0-ce
      - checkout
      - *install
      - *test

  generate_documentation:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/cxworker
    steps:
      - checkout
      - *ubuntu_install
      - *add_rw_key
      - *doc

workflows:
  version: 2
  test:
    jobs:
      - test_archlinux
      - generate_documentation:
          filters:
            branches:
              only: dev
          requires:
            - test_archlinux
