version: 2

references:

  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip curl
        pip3 install coveralls coverage

  install: &install
    run:
      name: Install dependencies and cxworker
      command: |
        pacman --noconfirm --needed -Syu minio
        mkdir examples/docker/cxflow_example/ssh
        echo $PRIVATE_SSH_KEY_PRIVATE | tr ' ' '\n' | base64 -d > examples/docker/cxflow_example/ssh/id_rsa
        pip install -r requirements.txt
        pip install .

  add_rw_key: &add_rw_key
    add_ssh_keys:
      fingerprints:
        - "bd:18:69:44:c4:97:94:f2:03:ba:db:dd:29:2e:cf:f2"

  test: &test
    run:
      name: Run tests.
      command: |
        tests/overall/test_bare.sh

  doc: &doc
    run:
      name: Generate documentation
      command: |
        bash <(curl -fsSL https://raw.githubusercontent.com/Cognexa/ci-utils/master/doc_deploy.sh)

jobs:

  test_archlinux:
    docker:
      - image: cognexa/cxflow:latest
    working_directory: ~/cxworker
    steps:
      - checkout
      - *install
      - *test

  generate_documentation:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/cxflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *add_rw_key
      - *doc

workflows:
  version: 2
  test:
    jobs:
      - test_archlinux
      - generate_documentation:
#          filters:
#            branches:
#              only: master
          requires:
            - test_archlinux
