version: "3.3"
services:
  registry:
    image: registry:2
    ports:
      - 6000:5000
  storage:
    image: minio/minio
    command: server /export
    ports:
      - 7000:9000
    volumes:
      - /tmp/minio/data:/export
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"