data_root: /tmp/worker-data
registry:
  url: http://0.0.0.0:6000
storage:
  url: http://0.0.0.0:7000
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

sheep:
  bare_sheep:
    port: 9001
    type: bare
    working_directory: examples/docker/cxflow_example
    stdout_file: /tmp/bare-cxworker-runner-stdout.txt
    stderr_file: /tmp/bare-cxworker-runner-stderr.txt
