registry:
  url: 0.0.0.0:6000
storage:
  url: 0.0.0.0:7000
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

containers:
  container_a:
    port: 9001
    type: nvidia
    devices:
      - /dev/nvidia0
  container_b:
    port: 9002
    type: nvidia
    devices:
      - /dev/nvidia1
