data_root: /tmp/worker-data
logging:
  level: debug
registry:
  url: http://0.0.0.0:6000
storage:
  url: http://0.0.0.0:7000
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

containers:
  container_a:
    port: 9001
    type: dummy
