logging:
  level: debug
registry:
  url: 0.0.0.0:6000
storage:
  url: 0.0.0.0:7000
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

containers:
  bare_container:
    port: 9001
    type: bare
    model_name: bare-cxflow
    model_version: latest
    config_path: config.yaml
    stdout_file: /tmp/bare-cxworker-runner-stdout.txt
    stderr_file: /tmp/bare-cxworker-runner-stderr.txt
    working_directory: examples/docker/cxflow_example
